### ISSUE TITLE
Request for Turkish Readme;

### ISSUE THREAD

**Issue by cagataycali** [btk/etimolojiturkce-api#1]
As you can understand from the title, it is imperative that this project has a Turkish document for Turkish I think.

Since the project was documented in English, it made me think that your target audience is Global. But in this project I think the target audience is Turkish developers.

If anything go wrong it will, most of Turkish developers don't have to have English skills to get understand what's going on this.

**Comment by btk** [comment]
You are totally right. My main reason to built this was because of my school work, and I was working with a foreign lecturer. And there is a lot of people from middle east visiting the website.

For my end, I don't think it is necessary for now to translate it, but if you would and open a pr, I would gladly merge. (Also if you do, the api can be accessed on https too.)

**Comment by emrecoban** [comment]
Created a new pull request about this issue, but couldn't achieve about linking the PR to this issue. I don't know why. You can check it here: [Fixed #1 Added Turkish translation for README file.](https://github.com/btk/etimolojiturkce-api/pull/2)
